export const TODOS = 'GET TODO LIST';

export const ADD_TODO = 'ADD NEW TODO';

export const REMOVE_TODO = 'REMOVE TODO LIST';

export const TOGGLE_TODO = 'CHANGE COMPLETED TODO';

export const SET_FILTER = 'FILTERS TODO ACCORDING TO STATE';